# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_card.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_P(object):
    def setupUi(self, Form_P):
        Form_P.setObjectName("Form_P")
        Form_P.resize(335, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_P.sizePolicy().hasHeightForWidth())
        Form_P.setSizePolicy(sizePolicy)
        Form_P.setMinimumSize(QtCore.QSize(335, 200))
        Form_P.setMaximumSize(QtCore.QSize(335, 200))
        self.gridLayout = QtWidgets.QGridLayout(Form_P)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form_P)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.part1 = QtWidgets.QLineEdit(Form_P)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.part1.setFont(font)
        self.part1.setFocusPolicy(QtCore.Qt.TabFocus)
        self.part1.setMaxLength(4)
        self.part1.setObjectName("part1")
        self.gridLayout.addWidget(self.part1, 1, 0, 1, 1)
        self.part2 = QtWidgets.QLineEdit(Form_P)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.part2.setFont(font)
        self.part2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.part2.setMaxLength(4)
        self.part2.setObjectName("part2")
        self.gridLayout.addWidget(self.part2, 1, 1, 1, 1)
        self.part3 = QtWidgets.QLineEdit(Form_P)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.part3.setFont(font)
        self.part3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.part3.setMaxLength(4)
        self.part3.setObjectName("part3")
        self.gridLayout.addWidget(self.part3, 1, 2, 1, 1)
        self.part4 = QtWidgets.QLineEdit(Form_P)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.part4.setFont(font)
        self.part4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.part4.setMaxLength(4)
        self.part4.setObjectName("part4")
        self.gridLayout.addWidget(self.part4, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form_P)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.part5 = QtWidgets.QLineEdit(Form_P)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.part5.setFont(font)
        self.part5.setFocusPolicy(QtCore.Qt.TabFocus)
        self.part5.setMaxLength(5)
        self.part5.setObjectName("part5")
        self.gridLayout.addWidget(self.part5, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form_P)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.part6 = QtWidgets.QLineEdit(Form_P)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.part6.setFont(font)
        self.part6.setFocusPolicy(QtCore.Qt.TabFocus)
        self.part6.setMaxLength(3)
        self.part6.setObjectName("part6")
        self.gridLayout.addWidget(self.part6, 2, 3, 1, 1)
        self.buy = QtWidgets.QPushButton(Form_P)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buy.setFont(font)
        self.buy.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buy.setObjectName("buy")
        self.gridLayout.addWidget(self.buy, 3, 0, 1, 4)

        self.retranslateUi(Form_P)
        QtCore.QMetaObject.connectSlotsByName(Form_P)

    def retranslateUi(self, Form_P):
        _translate = QtCore.QCoreApplication.translate
        Form_P.setWindowTitle(_translate("Form_P", "Оплата"))
        self.label.setText(_translate("Form_P", "Введите атрибуты карты"))
        self.label_3.setText(_translate("Form_P", "ММГГ"))
        self.label_2.setText(_translate("Form_P", "CVC2"))
        self.buy.setText(_translate("Form_P", "Оплатить и получить электронный билет"))
        self.buy.setShortcut(_translate("Form_P", "Return"))
