# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_cin.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_C(object):
    def setupUi(self, Dialog_C):
        Dialog_C.setObjectName("Dialog_C")
        Dialog_C.resize(500, 190)
        Dialog_C.setMinimumSize(QtCore.QSize(500, 190))
        Dialog_C.setMaximumSize(QtCore.QSize(500, 190))
        Dialog_C.setBaseSize(QtCore.QSize(500, 190))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_C)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.adr_lbl = QtWidgets.QLabel(Dialog_C)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adr_lbl.sizePolicy().hasHeightForWidth())
        self.adr_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.adr_lbl.setFont(font)
        self.adr_lbl.setObjectName("adr_lbl")
        self.gridLayout.addWidget(self.adr_lbl, 0, 1, 1, 1)
        self.adrs = QtWidgets.QLineEdit(Dialog_C)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adrs.sizePolicy().hasHeightForWidth())
        self.adrs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adrs.setFont(font)
        self.adrs.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.adrs.setObjectName("adrs")
        self.gridLayout.addWidget(self.adrs, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 4)
        self.del_cin_btn = QtWidgets.QPushButton(Dialog_C)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.del_cin_btn.setFont(font)
        self.del_cin_btn.setObjectName("del_cin_btn")
        self.gridLayout_2.addWidget(self.del_cin_btn, 3, 3, 1, 1)
        self.label = QtWidgets.QLabel(Dialog_C)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.add_cin_btn = QtWidgets.QPushButton(Dialog_C)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_cin_btn.sizePolicy().hasHeightForWidth())
        self.add_cin_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_cin_btn.setFont(font)
        self.add_cin_btn.setObjectName("add_cin_btn")
        self.gridLayout_2.addWidget(self.add_cin_btn, 3, 0, 1, 3)
        self.halls = QtWidgets.QComboBox(Dialog_C)
        self.halls.setObjectName("halls")
        self.gridLayout_2.addWidget(self.halls, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog_C)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.name = QtWidgets.QLineEdit(Dialog_C)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name.setFont(font)
        self.name.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 1, 0, 1, 2)
        self.add_hall_btn = QtWidgets.QPushButton(Dialog_C)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_hall_btn.setFont(font)
        self.add_hall_btn.setObjectName("add_hall_btn")
        self.gridLayout_2.addWidget(self.add_hall_btn, 1, 2, 1, 1)
        self.del_hall_btn = QtWidgets.QPushButton(Dialog_C)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.del_hall_btn.setFont(font)
        self.del_hall_btn.setObjectName("del_hall_btn")
        self.gridLayout_2.addWidget(self.del_hall_btn, 1, 3, 1, 1)

        self.retranslateUi(Dialog_C)
        QtCore.QMetaObject.connectSlotsByName(Dialog_C)

    def retranslateUi(self, Dialog_C):
        _translate = QtCore.QCoreApplication.translate
        Dialog_C.setWindowTitle(_translate("Dialog_C", "Управление кинотеатрами"))
        self.adr_lbl.setText(_translate("Dialog_C", " Адрес"))
        self.del_cin_btn.setText(_translate("Dialog_C", "Удалить"))
        self.label.setText(_translate("Dialog_C", "Название"))
        self.add_cin_btn.setText(_translate("Dialog_C", "Добавить кинотеатр"))
        self.add_cin_btn.setShortcut(_translate("Dialog_C", "Return"))
        self.label_2.setText(_translate("Dialog_C", "Залы"))
        self.add_hall_btn.setText(_translate("Dialog_C", "Добавить"))
        self.del_hall_btn.setText(_translate("Dialog_C", "Удалить"))
