# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sess.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_S(object):
    def setupUi(self, Dialog_S):
        Dialog_S.setObjectName("Dialog_S")
        Dialog_S.resize(780, 482)
        Dialog_S.setMinimumSize(QtCore.QSize(780, 450))
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog_S)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.genre_sql = QtWidgets.QLineEdit(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genre_sql.sizePolicy().hasHeightForWidth())
        self.genre_sql.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.genre_sql.setFont(font)
        self.genre_sql.setObjectName("genre_sql")
        self.gridLayout_2.addWidget(self.genre_sql, 8, 0, 1, 5)
        self.genre_cb = QtWidgets.QComboBox(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genre_cb.sizePolicy().hasHeightForWidth())
        self.genre_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.genre_cb.setFont(font)
        self.genre_cb.setObjectName("genre_cb")
        self.gridLayout_2.addWidget(self.genre_cb, 7, 2, 1, 3)
        self.dur_sql = QtWidgets.QLineEdit(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dur_sql.sizePolicy().hasHeightForWidth())
        self.dur_sql.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dur_sql.setFont(font)
        self.dur_sql.setObjectName("dur_sql")
        self.gridLayout_2.addWidget(self.dur_sql, 6, 0, 1, 5)
        self.label_5 = QtWidgets.QLabel(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 7, 0, 1, 2)
        self.year_sql = QtWidgets.QLineEdit(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_sql.sizePolicy().hasHeightForWidth())
        self.year_sql.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.year_sql.setFont(font)
        self.year_sql.setInputMask("")
        self.year_sql.setText("")
        self.year_sql.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.year_sql.setCursorPosition(0)
        self.year_sql.setObjectName("year_sql")
        self.gridLayout_2.addWidget(self.year_sql, 2, 0, 1, 5)
        self.label = QtWidgets.QLabel(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 3)
        self.year_cb = QtWidgets.QComboBox(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_cb.sizePolicy().hasHeightForWidth())
        self.year_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.year_cb.setFont(font)
        self.year_cb.setObjectName("year_cb")
        self.gridLayout_2.addWidget(self.year_cb, 1, 1, 1, 4)
        self.label_2 = QtWidgets.QLabel(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.title_sql = QtWidgets.QLineEdit(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_sql.sizePolicy().hasHeightForWidth())
        self.title_sql.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_sql.setFont(font)
        self.title_sql.setText("")
        self.title_sql.setObjectName("title_sql")
        self.gridLayout_2.addWidget(self.title_sql, 4, 0, 1, 5)
        self.label_4 = QtWidgets.QLabel(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 3)
        self.serch_btn = QtWidgets.QPushButton(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serch_btn.sizePolicy().hasHeightForWidth())
        self.serch_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.serch_btn.setFont(font)
        self.serch_btn.setObjectName("serch_btn")
        self.gridLayout_2.addWidget(self.serch_btn, 9, 0, 1, 5)
        self.add_film_btn = QtWidgets.QPushButton(Dialog_S)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_film_btn.setFont(font)
        self.add_film_btn.setObjectName("add_film_btn")
        self.gridLayout_2.addWidget(self.add_film_btn, 10, 0, 1, 5)
        self.title_le = QtWidgets.QLineEdit(Dialog_S)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_le.setFont(font)
        self.title_le.setObjectName("title_le")
        self.gridLayout_2.addWidget(self.title_le, 3, 3, 1, 2)
        self.dur_le = QtWidgets.QLineEdit(Dialog_S)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dur_le.setFont(font)
        self.dur_le.setObjectName("dur_le")
        self.gridLayout_2.addWidget(self.dur_le, 5, 3, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.table = QtWidgets.QTableWidget(Dialog_S)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.gridLayout_3.addWidget(self.table, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 1, 0, 1, 1)
        self.cinema_cb = QtWidgets.QComboBox(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cinema_cb.sizePolicy().hasHeightForWidth())
        self.cinema_cb.setSizePolicy(sizePolicy)
        self.cinema_cb.setObjectName("cinema_cb")
        self.gridLayout.addWidget(self.cinema_cb, 1, 1, 1, 1)
        self.hall_cb = QtWidgets.QComboBox(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hall_cb.sizePolicy().hasHeightForWidth())
        self.hall_cb.setSizePolicy(sizePolicy)
        self.hall_cb.setObjectName("hall_cb")
        self.gridLayout.addWidget(self.hall_cb, 1, 2, 1, 1)
        self.price_le = QtWidgets.QLineEdit(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_le.sizePolicy().hasHeightForWidth())
        self.price_le.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price_le.setFont(font)
        self.price_le.setPlaceholderText("")
        self.price_le.setObjectName("price_le")
        self.gridLayout.addWidget(self.price_le, 1, 3, 1, 1)
        self.add_sess = QtWidgets.QPushButton(Dialog_S)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_sess.sizePolicy().hasHeightForWidth())
        self.add_sess.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.add_sess.setFont(font)
        self.add_sess.setObjectName("add_sess")
        self.gridLayout.addWidget(self.add_sess, 2, 0, 1, 4)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 2)

        self.retranslateUi(Dialog_S)
        QtCore.QMetaObject.connectSlotsByName(Dialog_S)

    def retranslateUi(self, Dialog_S):
        _translate = QtCore.QCoreApplication.translate
        Dialog_S.setWindowTitle(_translate("Dialog_S", "Добавить сеанс"))
        self.genre_sql.setPlaceholderText(_translate("Dialog_S", "SQL запрос"))
        self.dur_sql.setPlaceholderText(_translate("Dialog_S", "SQL запрос"))
        self.label_5.setText(_translate("Dialog_S", "Жанр"))
        self.year_sql.setPlaceholderText(_translate("Dialog_S", "SQL запрос"))
        self.label.setText(_translate("Dialog_S", "Поиск фильма"))
        self.label_3.setText(_translate("Dialog_S", "Название"))
        self.label_2.setText(_translate("Dialog_S", "Год"))
        self.title_sql.setPlaceholderText(_translate("Dialog_S", "SQL запрос"))
        self.label_4.setText(_translate("Dialog_S", "Длительность"))
        self.serch_btn.setText(_translate("Dialog_S", "Найти"))
        self.add_film_btn.setText(_translate("Dialog_S", "Добавить фильм"))
        self.title_le.setPlaceholderText(_translate("Dialog_S", "введите текст"))
        self.dur_le.setPlaceholderText(_translate("Dialog_S", "введите текст"))
        self.label_6.setText(_translate("Dialog_S", "Дата и время сеанса"))
        self.label_7.setText(_translate("Dialog_S", "Кинотеатр"))
        self.label_8.setText(_translate("Dialog_S", "Зал"))
        self.label_9.setText(_translate("Dialog_S", "Цена билета, руб"))
        self.add_sess.setText(_translate("Dialog_S", "Добавить сеанс"))
